import keyMirror from 'key-mirror'

export default keyMirror({

  
  // ACTIONS
  

  SET_PLATFORM: null,
  SET_VERSION: null,

  SESSION_TOKEN_REQUEST: null,
  SESSION_TOKEN_SUCCESS: null,
  SESSION_TOKEN_FAILURE: null,

  DELETE_TOKEN_REQUEST: null,
  DELETE_TOKEN_SUCCESS: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  SET_SESSION_TOKEN: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  GET_CUSTOMERS_REQUEST: null, 
  GET_CUSTOMERS_SUCCESS: null, 
  GET_CUSTOMERS_FAILURE: null, 

  SET_CUSTOMER: null, 
  SET_JOB_CUSTOMER: null, 
  SET_INDEX: null,

  GET_BRANCH_REQUEST: null, 
  GET_BRANCH_SUCCESS: null, 
  GET_BRANCH_FAILURE: null, 

  SET_BRANCH: null, 
  SET_JOB_BRANCH: null, 

  GET_JOBS_REQUEST: null, 
  GET_JOBS_SUCCESS: null, 
  GET_JOBS_FAILURE: null, 

  GET_MAILS_REQUEST: null, 
  GET_MAILS_SUCCESS: null, 
  GET_MAILS_FAILURE: null, 

  GET_JOB_AREA: null, 
  
  SET_JOBS: null, 

  SET_SELECTED_JOB: null, 

  SET_MODAL: null, 
  
  SET_TYPE: null, 

  SET_DATE: null, 

  SET_PORT: null, 

  SET_AREA: null, 

  SET_INSPECTION_TYPE: null, 

  SET_EMPL: null, 

  SET_LINKED_PORT: null, 

  SET_LINKED_AREA: null, 

  SET_MMSI: null, 

  SET_PERSON: null, 

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null, 
  
  GET_JOB_DETAIL_REQUEST: null, 
  GET_JOB_DETAIL_SUCCESS: null, 
  GET_JOB_DETAIL_FAILURE: null,

  ON_CUSTOMER_REF_FIELD_CHANGE: null, 
  ON_YEAR_FIELD_CHANGE: null, 
  ON_VESSEL_FIELD_CHANGE: null, 

  GET_PORT_LIST_REQUEST: null, 
  GET_PORT_LIST_FAILURE: null, 
  GET_PORT_LIST_SUCCESS: null, 

  GET_AREA_LIST_REQUEST: null, 
  GET_AREA_LIST_SUCCESS: null, 
  GET_AREA_LIST_FAILURE: null, 

  GET_EMPL_LIST_REQUEST: null, 
  GET_EMPL_LIST_SUCCESS: null, 
  GET_EMPL_LIST_FAILURE: null,

// 
  //INSPECTION_TYPE: { DISCHARGING:'Discharging', LOADING:'Loading', OTHER: 'Other inspection' }
})
